name: 同步&合并
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:
  merge-branch:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
        with:
          persist-credentials: fals 

      - name: git-sync github/lxk0301/jd_scripts.git to github with private key
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:monk-coder/dust.git"
          source_branch: "master"
          destination_repo: "nxppru/diy"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
      - name: Merge gitee to main
        uses: devmasx/merge-branch@v1.3.1	
        if: env.PAT	
        with:	
          type: now	
          from_branch: master	
          target_branch: dev
          github_token: ${{ secrets.PAT }}
